# Generated by Django 5.1.3 on 2025-02-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='carretera',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carretera',
            name='ubicacion',
            field=models.CharField(max_length=500),
        ),
    ]
