# Generated by Django 5.1.3 on 2025-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0002_constructora_alter_carretera_longitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
